#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#define MAX_LINE_LENGTH 256
// Helper function to convert string to lowercase
void to_lower(char *str) {
    for (int i = 0; str[i]; i++) {
        str[i] = tolower((unsigned char)str[i]);
    }
}
// Helper function to remove "SYS_" prefix from syscall name
void remove_sys_prefix(char *dest, const char *src) {
    const char *prefix = "SYS_";
    if (strncmp(src, prefix, strlen(prefix)) == 0) {
        strcpy(dest, src + strlen(prefix));
    } else {
        strcpy(dest, src);
    }
}
int main(int argc, char *argv[]) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <output_file>\n", argv[0]);
        return 1;
    }
    // Open syscall.h for reading
    FILE *syscall_h = fopen("kernel/syscall.h", "r");
    if (!syscall_h) {
        fprintf(stderr, "Error opening syscall.h file\n");
        return 1;
    }
    // Open the user-provided output file
    FILE *output = fopen(argv[1], "w");
    if (!output) {
        fprintf(stderr, "Error creating %s file\n", argv[1]);
        fclose(syscall_h);
        return 1;
    }
    // Header in the output file
    fprintf(output, "# generated by usys.c - do not edit\n#include \"kernel/syscall.h\"\n");
    char line[MAX_LINE_LENGTH];
    char syscall_define[50]; // Stores the part after SYS_, e.g. "fork"
    char syscall_name[60]; // Increased size to avoid format-truncation warning (SYS_ + 49 chars + null)
   
    while (fgets(line, sizeof(line), syscall_h)) {
        // Look for lines starting with "#define SYS_"
        if (strncmp(line, "#define SYS_", 12) == 0) {
            // Extract the part after "SYS_" (e.g. "fork" from "#define SYS_fork")
            if (sscanf(line, "#define SYS_%49s", syscall_define) == 1) {
                // Build the full macro name for the li instruction: "SYS_<define>"
                snprintf(syscall_name, sizeof(syscall_name), "SYS_%s", syscall_define);
                // Derive function name: lowercase(define) without "SYS_"
                char temp_name[50];
                strcpy(temp_name, syscall_define); // temp_name = "fork"
                to_lower(temp_name); // temp_name = "fork"
                // Check for "// sys_prefix: 1" comment
                char *comment = strstr(line, "// sys_prefix: ");
                if (comment) {
                    int sys_prefix_flag = 0;
                    if (sscanf(comment, "// sys_prefix: %d", &sys_prefix_flag) == 1 && sys_prefix_flag == 1) {
                        // Add "sys_" prefix for exceptions
                        char prefixed[60];
                        snprintf(prefixed, sizeof(prefixed), "sys_%s", temp_name);
                        strcpy(temp_name, prefixed);
                    }
                }
                // Write the assembly stub
                fprintf(output, ".global %s\n", temp_name);
                fprintf(output, "%s:\n", temp_name);
                fprintf(output, " li a7, %s\n", syscall_name); // Use SYS_fork, not fork
                fprintf(output, " ecall\n");
                fprintf(output, " ret\n");
                fprintf(output, "\n"); // Blank line between stubs
            }
        }
    }
    fclose(syscall_h);
    fclose(output);
    printf("Assembly stubs successfully generated in %s.\n", argv[1]);
    return 0;
}