#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#define MAX_LINE_LENGTH 256

int main() {
    FILE *syscall_h = fopen("kernel/syscall.h", "r");
    if (!syscall_h) {
        fprintf(stderr, "Error opening syscall.h file\n");
        return 1;
    }

    FILE *output = fopen("user/usys.S", "w");
    if (!output) {
        fprintf(stderr, "Error creating usys.S file\n");
        fclose(syscall_h);
        return 1;
    }

    // Header in the output file
    fprintf(output, "# generated by usys.c - do not edit\n#include \"kernel/syscall.h\"\n");
    char line[MAX_LINE_LENGTH];
    while (fgets(line, sizeof(line), syscall_h)) {
        // Look for lines starting with "#define SYS_"
        if (strncmp(line, "#define SYS_", 12) == 0) {
            char syscall_name[50];
            int syscall_num;

            // Extract the system call name and number
            if (sscanf(line, "#define SYS_%s %d", syscall_name, &syscall_num) == 2) {
                // Write the assembly stub for this system call
                fprintf(output, ".global %s\n", syscall_name);
                fprintf(output, "%s:\n", syscall_name);
                fprintf(output, "  li a7, %d\n", syscall_num);  // Load syscall number into a7
                fprintf(output, "  ecall\n");                   // Make the syscall
                fprintf(output, "  ret\n\n");                   // Return
            }
        }
    }

    fclose(syscall_h);
    fclose(output);

    printf("Assembly stubs successfully generated in usys.S.\n");

    return 0;
}
